# Generated by Django 4.0.6 on 2022-08-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'двигатель',
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'марка',
            },
        ),
        migrations.CreateModel(
            name='Moto_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'модель',
            },
        ),
        migrations.CreateModel(
            name='Moto_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stroke_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('horse_power', models.PositiveSmallIntegerField()),
                ('cylinder_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.cylinder_amount')),
                ('displacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.displacement')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.engine')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.gear')),
                ('mark_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.marks')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_models')),
                ('moto_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_type')),
                ('stroke_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.stroke_amount')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.transmission')),
            ],
        ),
    ]
