# Generated by Django 4.0.6 on 2022-09-09 18:22

from django.db import migrations, models
import django.db.models.deletion
import storeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Цвет транспорта',
            },
        ),
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Объем двигателя в см3',
                'verbose_name_plural': 'Объем двигателя в см3',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'Марка мотоцикла',
            },
        ),
        migrations.CreateModel(
            name='Moto_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'Модель мотоцикла',
            },
        ),
        migrations.CreateModel(
            name='Moto_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Тип мотоцикла',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('mileage', models.PositiveIntegerField(verbose_name='Километраж')),
                ('horse_power', models.PositiveSmallIntegerField(verbose_name='Мощность, л.с')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(default='не указано ...', verbose_name='Комментарий')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.city', verbose_name='Город')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.color', verbose_name='Цвет транспорта')),
                ('displacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.displacement', verbose_name='Объем двигателя, см3')),
                ('mark_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.marks', verbose_name='Марка')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_models', verbose_name='Модель')),
                ('moto_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_type', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Трансмиссия',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=storeapp.models.offer_directory_path)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.motorcycle')),
            ],
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.transmission', verbose_name='Коробка передач'),
        ),
    ]
