# Generated by Django 4.0.6 on 2022-08-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cylinder_amount',
            options={'verbose_name_plural': 'Кол-во цилидров в двигателе'},
        ),
        migrations.AlterModelOptions(
            name='displacement',
            options={'verbose_name': 'значение', 'verbose_name_plural': 'Объем двигателя в см3'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'двигатель', 'verbose_name_plural': 'Тип двигателя'},
        ),
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name_plural': 'Механизм системы газораспределения'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'марка', 'verbose_name_plural': 'Марка мотоцикла'},
        ),
        migrations.AlterModelOptions(
            name='moto_models',
            options={'verbose_name': 'модель', 'verbose_name_plural': 'Модель мотоцикла'},
        ),
        migrations.AlterModelOptions(
            name='moto_type',
            options={'verbose_name_plural': 'Тип мотоцикла'},
        ),
        migrations.AlterModelOptions(
            name='motorcycles',
            options={'verbose_name': 'Мотоцикл', 'verbose_name_plural': 'Мотоциклы'},
        ),
        migrations.AlterModelOptions(
            name='stroke_amount',
            options={'verbose_name_plural': 'Тактов'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name_plural': 'Трансмиссия'},
        ),
        migrations.RenameField(
            model_name='displacement',
            old_name='integer',
            new_name='number',
        ),
    ]
