# Generated by Django 4.0.6 on 2022-08-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='horse_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
