# Generated by Django 4.0.6 on 2022-08-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_motorcycle_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='horse_power',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
