# Generated by Django 4.0.6 on 2022-10-16 18:38

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle_images',
            name='image',
            field=models.ImageField(upload_to=storeapp.models.offer_directory_path, verbose_name='Картинка'),
        ),
    ]
