# Generated by Django 4.0.6 on 2022-08-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_motorcycle_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.color', verbose_name='Цвет транспорта'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='comment',
            field=models.TextField(default='не указано ...', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='displacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.displacement', verbose_name='Объем двигателя, см3'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='horse_power',
            field=models.PositiveSmallIntegerField(verbose_name='Мощность, л.с'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='mark_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.marks', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Километраж'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_models', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='moto_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.moto_type', verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.transmission', verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
