# Generated by Django 4.0.6 on 2022-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_motorcycle_city_alter_motorcycle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
