# Generated by Django 4.0.6 on 2022-09-11 16:25

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeappuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=userapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='storeappuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
