# Generated by Django 4.0.6 on 2022-09-11 16:27

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_storeappuser_avatar_alter_storeappuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeappuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=userapp.models.user_directory_path),
        ),
    ]
