# Generated by Django 4.0.6 on 2022-10-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_storeappuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeappuser',
            name='telegram_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
